name: Runner CI

on:
  workflow_dispatch:
  #push:
  #  branches:
  #  - main
  #  - releases/*
  #  paths-ignore:
  #  - '**.md'
  #pull_request:
  #  branches:
  #  - '**'
  #  paths-ignore:
  #  - '**.md'

jobs:
  build:
    strategy:
      matrix:
        runtime: [ linux-x64 ]
        include:
        - runtime: linux-x64
          os: ubuntu-latest
          devScript: ./dev.sh

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

    # Build runner layout
    - name: Build & Layout Release
      run: |
        ${{ matrix.devScript }} layout Release ${{ matrix.runtime }}
      working-directory: src

    # Create runner package tar.gz/zip
    - name: Package Release
      if: github.event_name != 'pull_request'
      run: |
        ${{ matrix.devScript }} package Release
      working-directory: src

    # Upload runner package tar.gz/zip as artifact
    - name: Publish Artifact
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 #v4.4.3
      with:
        name: runner-package-${{ matrix.runtime }}
        path: |
          _package
